### ISSUE TITLE
Not working with FF 3.6 & 4.0

### ISSUE THREAD

**Issue by drpelz** [alterebro/jQuery.NiceFileInput.js#5]
Hi,

your plugin seems to be broken when I use it with FF 3.6 / 4.0 (Mac.)
The input file button is not recognized by FF.

Hope this helps...

BTW: Which browsers are supported (e.g. IE8+)?

**Comment by alterebro** [comment]
I see this is old... I cannot test those browsers anymore but the plugin was done using jQuery 1.7 which had IE>=6 support. No idea about the Firefox versions, sorry.
