### ISSUE TITLE
bower.json Name Invalid

### ISSUE THREAD

**Issue by rfludwick** [alterebro/jQuery.NiceFileInput.js#8]
The name field value of "alterebro/jQuery.NiceFileInput.js" in bower.json is throwing the following error for me:

Fatal error: Invalid name: "alterebro/jQuery.NiceFileInput.js"

Reportedly, this is now an invalid Bower name for newer versions of Bower.

**Comment by alterebro** [comment]
Thanks for noticing this up @rfludwick , name is now : jquery-nicefileinput

**Comment by rfpludwick** [comment]
You're welcome, @alterebro. And thank you for addressing it so quickly.
